# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# "Directory shim" Makefile. Each buildable directory should have a Makefile
# that defines TOCK_ON_TITAN and INVOKE_DIR then includes this Makefile. Purpose
# of the variables:
#   TOCK_ON_TITAN: The path to the root of the repository (where this file is)
#   INVOKE_DIR: The directory the user invoked make in.
#
# This Makefile plumbs the user's make requests through to the main Makefile,
# running the build for targets in (and under) the directory the user ran make
# in.

.PHONY: all
all: build

.PHONY: build
build:
	$(MAKE) -C $(TOCK_ON_TITAN) $(INVOKE_DIR)/build

.PHONY: check
check:
	$(MAKE) -C $(TOCK_ON_TITAN) $(INVOKE_DIR)/check

# "clean" is a repository-wide command: it always cleans up all build artifacts
# for the repository, rather than trying to only clean up artifacts generated by
# this directory (and the transitive closure of its dependencies).
.PHONY: clean
clean:
	$(MAKE) -C $(TOCK_ON_TITAN) clean

.PHONY: devicetests
devicetests:
	$(MAKE) -C $(TOCK_ON_TITAN) $(INVOKE_DIR)/devicetests

.PHONY: doc
doc:
	$(MAKE) -C $(TOCK_ON_TITAN) $(INVOKE_DIR)/doc

.PHONY: localtests
localtests:
	$(MAKE) -C $(TOCK_ON_TITAN) $(INVOKE_DIR)/localtests

.PHONY: program
program:
	$(MAKE) -C $(TOCK_ON_TITAN) $(INVOKE_DIR)/program

.PHONY: prtest
prtest:
	$(MAKE) -C $(TOCK_ON_TITAN) prtest

.PHONY: run
run:
	$(MAKE) -C $(TOCK_ON_TITAN) $(INVOKE_DIR)/run
