.PHONY: target/target/release/golf
target/target/release/golf:
	@cargo build --release --target=../../chips/hotel/target.json

.PHONY: doc
doc:
	@cargo doc --target=../../chips/hotel/target.json

.PHONY: clean
clean:
	@cargo clean

